- name: create data dir
  ansible.builtin.file:
    path: "/opt/retronas/data"
    mode: 0755
    owner: root
    group: root
    state: directory
  delegate_to: localhost

- name: grab retronas systems
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/retronas/systems/main/systems.yml
    dest: "{{ systems }}"
  delegate_to: localhost

- name: include systems vars
  include_vars: "{{ systems }}"
